### ISSUE TITLE
http://start.grails.org/appData/ page gives internal error http 500 code

### ISSUE THREAD

**Issue by ant-druha** [grails-samples/grails-forge#12]
We also started getting reports about IntelliJ IDEA project wizard not working for Application Forge:

![image](https://user-images.githubusercontent.com/3117044/85732374-fc115280-b703-11ea-9eeb-55152676bb49.png)

See also a Grails community [slack thread](https://grails.slack.com/archives/C07M0GTDE/p1593071316226600).

**Comment by ant-druha** [comment]
Any updates on this issue?

**Comment by puneetbehl** [comment]
It should be working now.

**Comment by nekiala** [comment]
Same problem here on 2021/10/15.
