### ISSUE TITLE
When creating a new app with start.grails.org empty folders are not created

### ISSUE THREAD

**Issue by sdelamo** [grails-samples/grails-forge#3]
I just created a new app with [start.grails.org](http://start.grails.org) form. 

Empty folders such as 

    grails-app/domain 
    grails-app/services
    src/test
    src/integration-test

are not created

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails-samples/grails-forge/commit/b83b3b18133bf8491c8012e7806a7ff9dbf4d1c2
