### ISSUE TITLE
start.grails.org is throwing an error when attempting to create a project

### ISSUE THREAD

**Issue by jeffbrown** [grails-samples/grails-forge#7]
~ $ curl -O start.grails.org/myapp.zip -d version=3.3.9
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100    60  100    47  100    13    225     62 --:--:-- --:--:-- --:--:--   224
    ~ $ 
    ~ $ cat myapp.zip 
    {"message":"Internal server error","error":500}
    ~ $

Similar happens when using the browser interface.

**Comment by ilopmar** [comment]
Last time something like this happended @sdelamo took a look at the logs and restarted the instance. I don't have access to PFC so I can't check the logs.

**Comment by ilopmar** [comment]
It is working now. I will leave this open and coordinate with Sergio to fix this so it doesn't happen anymore.

**Comment by ilopmar** [comment]
The root cause is that the disk gets full because not all temporal files are cleaned up after generating a project. We delete a few of them:

```
| Application created at /tmp/groovy-generated-8584865727937600121-tmpdir/myapp
2018-12-27 09:37:31.385  INFO --- [nio-8080-exec-8] g.a.c.appgenerator.GeneratorController   : Deleting project file [/tmp/tmp_5319297785137290556grails]
```

But for every project created the following directories are created with a total size of ~7MB:
```
drwxrwxr-x 3 ivan ivan   4096 Dec 27 09:37 groovy-generated-216831950569688527-tmpdir
drwxrwxr-x 3 ivan ivan   4096 Dec 27 09:37 groovy-generated-3521769282147845157-tmpdir
drwxrwxr-x 3 ivan ivan   4096 Dec 27 09:37 groovy-generated-7799516170708456597-tmpdir
drwxrwxr-x 3 ivan ivan   4096 Dec 27 09:37 groovy-generated-7582271551453757704-tmpdir
drwxrwxr-x 3 ivan ivan   4096 Dec 27 09:37 groovy-generated-1496474996537922876-tmpdir
drwxrwxr-x 3 ivan ivan   4096 Dec 27 09:37 groovy-generated-3954602656112729914-tmpdir
drwxrwxr-x 2 ivan ivan   4096 Dec 27 09:37 groovy-generated-8584865727937600121-tmpdir
```

**Comment by ilopmar** [comment]
As the fix in https://github.com/grails/grails-core/pull/11209 only applies to Grails 3.3.10+ and Grails 4.0.0+ applications I've created the following job to cleanup the temporar directories: https://github.com/grails-samples/grails-forge/blob/v1.7.0/grails-app/services/appgenerator/CleanupJobService.groovy

It's already deployed and I've checked that everything is working as expected.
